package com.checkout.payments;

import com.checkout.common.CountryCode;
import lombok.Data;

import java.util.List;

@Data
public final class PaymentProcessing {

    /**
     * A unique identifier for the authorization submitted to the card scheme during processing.
     * [Optional]
     */
    private String retrievalReferenceNumber;

    /**
     * A unique identifier for the transaction generated by the acquirer.
     * [Optional]
     */
    private String acquirerTransactionId;

    /**
     * The name of the acquirer that processed the payment.
     * [Optional]
     */
    private String acquirerName;

    /**
     * The two-letter ISO country code of the acquirer country.
     * [Optional]
     */
    private CountryCode acquirerCountryCode;

    /**
     * A code representing the recommended follow-up action for the payment, as provided by Checkout.com.
     * [Optional]
     */
    private String recommendationCode;

    /**
     * The scheme the transaction was processed with.
     * [Optional]
     */
    private String scheme;

    /**
     * The Merchant Advice Code (MAC) provided by Mastercard with additional transaction information.
     * [Optional]
     */
    private String partnerMerchantAdviceCode;

    /**
     * The original authorization response code sent by the scheme (raw response code).
     * [Optional]
     */
    private String partnerResponseCode;

    /**
     * Unique order identification of an Afterpay payment.
     * [Optional]
     */
    private String partnerOrderId;

    /**
     * The partner session identifier associated with the payment.
     * [Optional]
     */
    private String partnerSessionId;

    /**
     * The client token returned by the partner for client-side initialization.
     * [Optional]
     */
    private String partnerClientToken;

    /**
     * Unique identification of a payment provided by partner.
     * [Optional]
     */
    private String partnerPaymentId;

    /**
     * The type of Primary Account Number (PAN) used: fpan (full card) or dpan (network token).
     * [Optional]
     * Enum: "fpan" "dpan"
     */
    private PanProcessedType panTypeProcessed;

    /**
     * A payload used to continue processing for multi-step payment flows.
     * [Optional]
     */
    private String continuationPayload;

    /**
     * The Payment Unique Number (PUN) assigned to the payment.
     * [Optional]
     */
    private String pun;

    /**
     * The status of the payment as reported by the partner.
     * [Optional]
     */
    private String partnerStatus;

    /**
     * Unique transaction identification provided by partner.
     * [Optional]
     */
    private String partnerTransactionId;

    /**
     * Error codes provided by the partner for a failed or declined payment.
     * [Optional]
     */
    private List<String> partnerErrorCodes;

    /**
     * Error description provided by the partner.
     * [Optional]
     */
    private String partnerErrorMessage;

    /**
     * Authorization code provided by the partner.
     * [Optional]
     */
    private String partnerAuthorizationCode;

    /**
     * Authorization response code provided by the partner.
     * [Optional]
     */
    private String partnerAuthorizationResponseCode;

    /**
     * Surcharge amount applied to the transaction in minor currency units.
     * [Optional]
     */
    private Long surchargeAmount;

    /**
     * Indicates whether a Checkout.com Network Token was available for the payment.
     * [Optional]
     */
    private Boolean ckoNetworkTokenAvailable;

    /**
     * The country where the purchase was made. ISO 3166-1 alpha-2 country code.
     * [Optional]
     * max 2 characters
     */
    private CountryCode purchaseCountry;

    /**
     * The merchant identifier configured with the scheme and used for the payment.
     * [Optional]
     */
    private String schemeMerchantId;

    /**
     * The foreign retailer amount applied by the merchant, in minor currency units.
     * [Optional]
     */
    private Long foreignRetailerAmount;

    /**
     * Indicates whether a network token should be provisioned for the payment.
     * [Optional]
     */
    private Boolean provisionNetworkToken;

    /**
     * The merchant category code (MCC) associated with the payment.
     * [Optional]
     */
    private String merchantCategoryCode;

    /**
     * Indicates whether this is an Account Funding Transaction (AFT).
     * [Optional]
     */
    private Boolean aft;

    /**
     * The Bizum payment identifier returned when processing a Bizum payment.
     * [Optional]
     */
    private String bizumPaymentId;

    /**
     * A reconciliation identifier for the payment.
     * [Optional]
     */
    private String reconciliationId;

    /**
     * The aggregator information for this payment.
     * [Optional]
     */
    private Aggregator aggregator;

}
