package com.checkout.handlepaymentsandpayouts.setups.entities.paymentMethods.blik;

import com.checkout.handlepaymentsandpayouts.setups.entities.paymentMethods.common.PaymentMethodBase;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * The Blik payment method's details and configuration.
 */
@Data
@EqualsAndHashCode(callSuper = true)
public final class Blik extends PaymentMethodBase {

    /**
     * The 6-digit BLIK code generated by the customer's banking app.
     * [Optional] writeOnly
     * Pattern: ^[0-9]{6}$
     */
    private String partnerCode;
}
