package com.checkout.common;

import com.google.gson.annotations.SerializedName;
import org.apache.commons.lang3.EnumUtils;

public enum CountryCode {

    @SerializedName("AF")
    AF("93"),
    @SerializedName("AX")
    AX("35818"),
    @SerializedName("AL")
    AL("355"),
    @SerializedName("DZ")
    DZ("213"),
    @SerializedName("AS")
    AS("1684"),
    @SerializedName("AD")
    AD("376"),
    @SerializedName("AO")
    AO("244"),
    @SerializedName("AI")
    AI("1264"),
    @SerializedName("AG")
    AG("1268"),
    @SerializedName("AR")
    AR("54"),
    @SerializedName("AM")
    AM("374"),
    @SerializedName("AW")
    AW("297"),
    @SerializedName("AC")
    AC("247"),
    @SerializedName("AU")
    AU("61"),
    @SerializedName("AQ")
    AQ("672"),
    @SerializedName("AT")
    AT("43"),
    @SerializedName("AZ")
    AZ("994"),
    @SerializedName("BS")
    BS("1242"),
    @SerializedName("BH")
    BH("973"),
    @SerializedName("BD")
    BD("880"),
    @SerializedName("BB")
    BB("1246"),
    @SerializedName("BY")
    BY("375"),
    @SerializedName("BE")
    BE("32"),
    @SerializedName("BZ")
    BZ("501"),
    @SerializedName("BJ")
    BJ("229"),
    @SerializedName("BM")
    BM("1441"),
    @SerializedName("BT")
    BT("975"),
    @SerializedName("BO")
    BO("591"),
    @SerializedName("BQ")
    BQ("5997"),
    @SerializedName("BA")
    BA("387"),
    @SerializedName("BW")
    BW("267"),
    @SerializedName("BV")
    BV(""),
    @SerializedName("BR")
    BR("55"),
    @SerializedName("IO")
    IO("2"),
    @SerializedName("VG")
    VG("1284"),
    @SerializedName("BN")
    BN("673"),
    @SerializedName("BG")
    BG("359"),
    @SerializedName("BF")
    BF("226"),
    @SerializedName("BI")
    BI("257"),
    @SerializedName("KH")
    KH("855"),
    @SerializedName("CM")
    CM("237"),
    @SerializedName("CA")
    CA("1"),
    @SerializedName("CV")
    CV("238"),
    @SerializedName("KY")
    KY("1345"),
    @SerializedName("CF")
    CF("236"),
    @SerializedName("TD")
    TD("235"),
    @SerializedName("CL")
    CL("56"),
    @SerializedName("CN")
    CN("86"),
    @SerializedName("TW")
    TW("886"),
    @SerializedName("CX")
    CX("61"),
    @SerializedName("PF")
    PF("689"),
    @SerializedName("CC")
    CC("61"),
    @SerializedName("CO")
    CO("57"),
    @SerializedName("KM")
    KM("269"),
    @SerializedName("CG")
    CG("242"),
    @SerializedName("CD")
    CD("243"),
    @SerializedName("CK")
    CK("682"),
    @SerializedName("CR")
    CR("506"),
    @SerializedName("CI")
    CI("225"),
    @SerializedName("HR")
    HR("385"),
    @SerializedName("CU")
    CU("53"),
    @SerializedName("CW")
    CW("5999"),
    @SerializedName("CY")
    CY("357"),
    @SerializedName("CZ")
    CZ("420"),
    @SerializedName("DK")
    DK("45"),
    @SerializedName("DJ")
    DJ("253"),
    @SerializedName("DM")
    DM("1767"),
    @SerializedName("DO")
    DO("1809"),
    @SerializedName("EC")
    EC("593"),
    @SerializedName("EG")
    EG("20"),
    @SerializedName("SV")
    SV("503"),
    @SerializedName("GQ")
    GQ("240"),
    @SerializedName("ER")
    ER("291"),
    @SerializedName("EE")
    EE("372"),
    @SerializedName("SZ")
    SZ("268"),
    @SerializedName("ET")
    ET("251"),
    @SerializedName("FK")
    FK("500"),
    @SerializedName("FO")
    FO("298"),
    @SerializedName("FJ")
    FJ("679"),
    @SerializedName("FI")
    FI("358"),
    @SerializedName("FR")
    FR("33"),
    @SerializedName("GF")
    GF("594"),
    @SerializedName("TF")
    TF("590"),
    @SerializedName("GA")
    GA("241"),
    @SerializedName("GM")
    GM("220"),
    @SerializedName("GE")
    GE("995"),
    @SerializedName("DE")
    DE("49"),
    @SerializedName("GH")
    GH("223"),
    @SerializedName("GI")
    GI("350"),
    @SerializedName("GR")
    GR("30"),
    @SerializedName("GL")
    GL("299"),
    @SerializedName("GD")
    GD("1473"),
    @SerializedName("GP")
    GP("590"),
    @SerializedName("GU")
    GU("1671"),
    @SerializedName("GT")
    GT("502"),
    @SerializedName("GG")
    GG("441481"),
    @SerializedName("GN")
    GN("224"),
    @SerializedName("GW")
    GW("245"),
    @SerializedName("GY")
    GY("592"),
    @SerializedName("HT")
    HT("509"),
    @SerializedName("HM")
    HM(""),
    @SerializedName("HN")
    HN("504"),
    @SerializedName("HK")
    HK("852"),
    @SerializedName("HU")
    HU("36"),
    @SerializedName("IS")
    IS("354"),
    @SerializedName("IN")
    IN("91"),
    @SerializedName("ID")
    ID("62"),
    @SerializedName("IR")
    IR("98"),
    @SerializedName("IQ")
    IQ("964"),
    @SerializedName("IE")
    IE("353"),
    @SerializedName("IM")
    IM("44"),
    @SerializedName("IL")
    IL("972"),
    @SerializedName("IT")
    IT("39"),
    @SerializedName("JM")
    JM("1876"),
    @SerializedName("JP")
    JP("81"),
    @SerializedName("JE")
    JE("44"),
    @SerializedName("JO")
    JO("962"),
    @SerializedName("KZ")
    KZ("7"),
    @SerializedName("KE")
    KE("254"),
    @SerializedName("KI")
    KI("686"),
    @SerializedName("KP")
    KP("850"),
    @SerializedName("KR")
    KR("82"),
    @SerializedName("KW")
    KW("965"),
    @SerializedName("KG")
    KG("996"),
    @SerializedName("LA")
    LA("856"),
    @SerializedName("LV")
    LV("371"),
    @SerializedName("LB")
    LB("961"),
    @SerializedName("LS")
    LS("266"),
    @SerializedName("LR")
    LR("231"),
    @SerializedName("LY")
    LY("218"),
    @SerializedName("LI")
    LI("423"),
    @SerializedName("LT")
    LT("370"),
    @SerializedName("LU")
    LU("352"),
    @SerializedName("MO")
    MO("853"),
    @SerializedName("MK")
    MK("389"),
    @SerializedName("MG")
    MG("261"),
    @SerializedName("MW")
    MW("265"),
    @SerializedName("MY")
    MY("60"),
    @SerializedName("MV")
    MV("960"),
    @SerializedName("ML")
    ML("223"),
    @SerializedName("MT")
    MT("356"),
    @SerializedName("MH")
    MH("692"),
    @SerializedName("MQ")
    MQ("596"),
    @SerializedName("MR")
    MR("222"),
    @SerializedName("MU")
    MU("230"),
    @SerializedName("YT")
    YT("262"),
    @SerializedName("MX")
    MX("52"),
    @SerializedName("FM")
    FM("691"),
    @SerializedName("MD")
    MD("372"),
    @SerializedName("MC")
    MC("377"),
    @SerializedName("MN")
    MN("976"),
    @SerializedName("ME")
    ME("382"),
    @SerializedName("MS")
    MS("1664"),
    @SerializedName("MA")
    MA("212"),
    @SerializedName("MZ")
    MZ("258"),
    @SerializedName("MM")
    MM("95"),
    @SerializedName("NA")
    NA("264"),
    @SerializedName("NR")
    NR("674"),
    @SerializedName("NP")
    NP("977"),
    @SerializedName("NL")
    NL("31"),
    @SerializedName("AN")
    AN("599"),
    @SerializedName("NC")
    NC("687"),
    @SerializedName("NZ")
    NZ("64"),
    @SerializedName("NI")
    NI("505"),
    @SerializedName("NE")
    NE("227"),
    @SerializedName("NG")
    NG("234"),
    @SerializedName("NU")
    NU("683"),
    @SerializedName("NF")
    NF("672"),
    @SerializedName("MP")
    MP("1670"),
    @SerializedName("NO")
    NO("47"),
    @SerializedName("OM")
    OM("968"),
    @SerializedName("PK")
    PK("92"),
    @SerializedName("PW")
    PW("680"),
    @SerializedName("PA")
    PA("507"),
    @SerializedName("PG")
    PG("675"),
    @SerializedName("PY")
    PY("595"),
    @SerializedName("PE")
    PE("51"),
    @SerializedName("PH")
    PH("63"),
    @SerializedName("PN")
    PN("870"),
    @SerializedName("PL")
    PL("48"),
    @SerializedName("PT")
    PT("351"),
    @SerializedName("PR")
    PR("1787"),
    @SerializedName("QA")
    QA("974"),
    @SerializedName("RE")
    RE("262"),
    @SerializedName("RO")
    RO("40"),
    @SerializedName("RU")
    RU("7"),
    @SerializedName("RW")
    RW("250"),
    @SerializedName("BL")
    BL("590"),
    @SerializedName("SH")
    SH("290"),
    @SerializedName("KN")
    KN("1869"),
    @SerializedName("LC")
    LC("1758"),
    @SerializedName("MF")
    MF("1599"),
    @SerializedName("PM")
    PM("508"),
    @SerializedName("VC")
    VC("1784"),
    @SerializedName("WS")
    WS("685"),
    @SerializedName("SM")
    SM("378"),
    @SerializedName("ST")
    ST("239"),
    @SerializedName("SA")
    SA("966"),
    @SerializedName("SN")
    SN("221"),
    @SerializedName("RS")
    RS("381"),
    @SerializedName("SC")
    SC("248"),
    @SerializedName("SL")
    SL("232"),
    @SerializedName("SG")
    SG("65"),
    @SerializedName("SX")
    SX("1721"),
    @SerializedName("SK")
    SK("421"),
    @SerializedName("SI")
    SI("386"),
    @SerializedName("SB")
    SB("677"),
    @SerializedName("SO")
    SO("252"),
    @SerializedName("ZA")
    ZA("27"),
    @SerializedName("GS")
    GS("500"),
    @SerializedName("SS")
    SS("211"),
    @SerializedName("ES")
    ES("34"),
    @SerializedName("LK")
    LK("94"),
    @SerializedName("SD")
    SD("249"),
    @SerializedName("SR")
    SR("597"),
    @SerializedName("SJ")
    SJ("4779"),
    @SerializedName("SE")
    SE("46"),
    @SerializedName("CH")
    CH("41"),
    @SerializedName("SY")
    SY("963"),
    @SerializedName("TJ")
    TJ("992"),
    @SerializedName("TZ")
    TZ("255"),
    @SerializedName("TH")
    TH("66"),
    @SerializedName("TL")
    TL("670"),
    @SerializedName("TG")
    TG("228"),
    @SerializedName("TK")
    TK("690"),
    @SerializedName("TO")
    TO("676"),
    @SerializedName("TT")
    TT("1868"),
    @SerializedName("TA")
    TA("2908"),
    @SerializedName("TN")
    TN("216"),
    @SerializedName("TR")
    TR("90"),
    @SerializedName("TM")
    TM("993"),
    @SerializedName("TC")
    TC("1649"),
    @SerializedName("TV")
    TV("688"),
    @SerializedName("VI")
    VI("1340"),
    @SerializedName("UG")
    UG("256"),
    @SerializedName("UA")
    UA("380"),
    @SerializedName("AE")
    AE("971"),
    @SerializedName("GB")
    GB("44"),
    @SerializedName("US")
    US("1"),
    @SerializedName("UY")
    UY("598"),
    @SerializedName("UZ")
    UZ("998"),
    @SerializedName("VU")
    VU("678"),
    @SerializedName("VA")
    VA("39"),
    @SerializedName("VE")
    VE("58"),
    @SerializedName("VN")
    VN("84"),
    @SerializedName("UM")
    UM("1808"),
    @SerializedName("WF")
    WF("681"),
    @SerializedName("EH")
    EH("2125288"),
    @SerializedName("YE")
    YE("967"),
    @SerializedName("ZM")
    ZM("260"),
    @SerializedName("ZW")
    ZW("263");

    private String dialCode;

    CountryCode(final String dialCode) {
        this.dialCode = dialCode;
    }

    public static CountryCode fromString(final String countryCode) {
        if (EnumUtils.isValidEnum(CountryCode.class, countryCode)) {
            return CountryCode.valueOf(countryCode);
        } else {
            return null;
        }
    }

}

