package com.checkout.common;

import com.google.gson.annotations.SerializedName;

public enum PaymentSourceType {

    @SerializedName("ach")
    ACH,
    @SerializedName("afterpay")
    AFTERPAY,
    @SerializedName("alipay")
    ALIPAY,
    @SerializedName("alipay_cn")
    ALIPAY_CN,
    @SerializedName("alipay_hk")
    ALIPAY_HK,
    @SerializedName("alipay_plus")
    ALIPAY_PLUS,
    @SerializedName("alma")
    ALMA,
    @SerializedName("applepay")
    APPLEPAY,
    @SerializedName("bancontact")
    BANCONTACT,
    @SerializedName("bank_account")
    BANK_ACCOUNT,
    @SerializedName("benefit")
    BENEFIT,
    @SerializedName("benefitpay")
    BENEFITPAY,
    @SerializedName("bizum")
    BIZUM,
    @SerializedName("boleto")
    BOLETO,
    @SerializedName("card")
    CARD,
    @SerializedName("currency_account")
    CURRENCY_ACCOUNT,
    @SerializedName("customer")
    CUSTOMER,
    @SerializedName("cvconnect")
    CV_CONNECT,
    @SerializedName("dana")
    DANA,
    @SerializedName("dlocal")
    DLOCAL,
    @SerializedName("eps")
    EPS,
    @SerializedName("fawry")
    FAWRY,
    @SerializedName("gcash")
    GCASH,
    @SerializedName("giropay")
    GIROPAY,
    @SerializedName("googlepay")
    GOOGLEPAY,
    @SerializedName("id")
    ID,
    @SerializedName("ideal")
    IDEAL,
    @SerializedName("illicado")
    ILLICADO,
    @SerializedName("kakaopay")
    KAKAOPAY,
    @SerializedName("klarna")
    KLARNA,
    @SerializedName("knet")
    KNET,
    @SerializedName("mbway")
    MBWAY,
    @SerializedName("multibanco")
    MULTIBANCO,
    @SerializedName("network_token")
    NETWORK_TOKEN,
    @SerializedName("octopus")
    OCTOPUS,
    @SerializedName("oxxo")
    OXXO,
    @SerializedName("p24")
    P24,
    @SerializedName("pagofacil")
    PAGOFACIL,
    @SerializedName("paypal")
    PAYPAL,
    @SerializedName("plaid")
    PLAID,
    @SerializedName("poli")
    POLI,
    @SerializedName("postfinance")
    POSTFINANCE,
    @SerializedName("provider_token")
    PROVIDER_TOKEN,
    @SerializedName("qpay")
    QPAY,
    @SerializedName("rapipago")
    RAPIPAGO,
    @SerializedName("id")
    SEPA,
    @SerializedName("sepa")
    SEPAV4,
    @SerializedName("sequra")
    SEQURA,
    @SerializedName("sofort")
    SOFORT,
    @SerializedName("stcpay")
    STCPAY,
    @SerializedName("tabby")
    TABBY,
    @SerializedName("tamara")
    TAMARA,
    @SerializedName("token")
    TOKEN,
    @SerializedName("tng")
    TNG,
    @SerializedName("truemoney")
    TRUEMONEY,
    @SerializedName("trustly")
    TRUSTLY,
    @SerializedName("wechatpay")
    WECHATPAY
}
